id: P41BC02AB
initial_creation_type: input
source_metadata:
  title: Dharma Protectors Series
  language: zh
  description: 'The following texts are now available as part of our Dharma Protectors
    (dharmapāla; Tib. chos skyong) series:'
  volume:
    ccd4bd4762e342d6a16287de1b6c5ec0:
      title: Brief Dharmapālas Offering
      parent: General
    dd7456b9e75148769caf9e4db851ddf5:
      title: Brief Protectors Practice
      parent: General
    abd26ddffdd74f0aac9d6c1901efa85a:
      title: Expeditious Activity Torma Offering
      parent: General
    ec323cd8778b403b97d57b52bc72071b:
      title: Wayfaring Offering
      parent: General
    054440f8d3f54db6935bade93781e2a7:
      title: A Practice of Fulfilment and Confession to an Ocean of Oath-bound Protectors
      parent: General
    15fb576a67484cf1b00a272ce11f71d4:
      title: 'Damchen Chitor: A Brief Practice of Torma Offering to the Oath-Bound
        Guardians'
      parent: General
    00803cec4b0345e08bb35545a7fc35ac:
      title: Offering Prayer to Changshönma, Protectress Riding upon a Wolf
      parent: Changshönma
    dbebed539f0140ca9dba4bbfc9eff9e9:
      title: Brief Offering Prayer to Durtrö Lhamo, Mistress of the Charnel Ground
      parent: Durtrö Lhamo
    4127724a098044848a3372dd53e58ef6:
      title: Golden Drink (Serkyem) and Torma Offering
      parent: Eight Classes
    3615ffa5773b403fb8b9e0eb06129a15:
      title: Restorative Offering to the Eight Classes
      parent: Eight Classes
    4b4262c2edc94f74a894995c3af2f1dd:
      title: Brief Offering Prayer to Ekajaṭī
      parent: Ekajaṭī
    d59be926f4d242ddb406a6cd08d8674b:
      title: Offering to the Five Medicine Sisters, Guardians of the Earth
      parent: Five Medicine Sisters
    ae738cc7c2374ff1a94537da020a7b66:
      title: Petitionary Offering to Norbu Dradül Tsal
      parent: Gesar
    23f65a76586f4bd4a137a49c759a449a:
      title: Brief Offering Prayer to Gesar
      parent: Gesar
    8e6b01aedc204151a989a84d9dbe4575:
      title: 'Sweet Melody to Delight the Glorious Deity: In Praise of Śrī Kālīdevī'
      parent: Kālīdevī
    062c4d726f71423face7c97871eeb4f8:
      title: 'Swift Enlightened Activity: A Concise Ceremony of Offering and Prayer
        to Mahākāla and Consort'
      parent: Mahākāla
    9e080487978346ae8a870478584619c1:
      title: 'The Fulfilment of All Wishes: Prayer and Entrustment of Activity to
        the Glorious Guru Mahākāla Pañjaranātha'
      parent: Mahākāla
    f6cca04cfa3346adb461dd978230a334:
      title: 'Bestower of Supreme Accomplishment: A Torma Offering to Mahākāla'
      parent: Mahākāla
    ac99765aa119442ab2894a7a754f31e0:
      title: 'Pacifying the Turmoil of the Mamos: A Concise Liturgy'
      parent: Pacifying the Turmoil of the Mamos
    06d0886f1a9345209d678522d38526cd:
      title: Brief Prayer for Pacifying the Turmoil of the Mamos
      parent: Pacifying the Turmoil of the Mamos
    5c45d0dbdabe44e5a505ad43fde21dab:
      title: A Brief Petitionary Offering to the Mātṛkā Pukkasī, Local Protectress
        of the Jarung Kashor Stūpa
      parent: Pukkasī
    0ea7aef6bab04e82b85c6e80d1ac9d2d:
      title: Brief Offering Prayer to Za Rāhula
      parent: Rāhula
    f370ef52e51a499c97af1ef56aa42827:
      title: Serkyem (Golden Libation) Offering to the Guardians of the Tradition
      parent: Serkyem
    2f404800bf2f4718ae5a3e5c59fdf6e1:
      title: Brief Offering Prayer to Tsiu Marpo
      parent: Tsiu Marpo
    e7a9db59fa8e4b9798f70a74e2c6bdb4:
      title: Brief Offering Prayer to the Oath-Bound Vajrasādhu
      parent: Vajrasādhu
    3ac4196215e04d37a88f24e1cff7dab3:
      title: Yarlha Shampo Sang Offering
      parent: Yarlha Shampo
created_at: '2022-03-01T03:27:20.285044'
last_modified_at: '2022-03-01T03:27:20.285046'
